function [fitresult, gof] = aGeneratedFit(x, y,WoOrder)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Nov-2019 19:17:54

V=WoOrder(1).Y;
h1=histogram(V,ceil(sqrt(length(V))),'Normalization','probability');
%ceil(sqrt(length(V))),
x=h1.BinEdges-h1.BinWidth/2;
x(1)=[];
y=h1.Values;
bin_width=h1.BinWidth;

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '(1/sqrt(2*pi*s^2))*exp(-(x-m).^2/(2*s^2))*bin_width', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [bin_width -inf];
opts.StartPoint = [bin_width 20];
opts.Upper = [bin_width inf];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


