function [fitresult, gof] = createFitRay(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'Ray' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2019 19:20:24


%% Fit: 'Ray'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '((x./s^2).*exp(-x.^2./(2*s^2)))*bin_width', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.8002804688888 0.913375856139019];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ray' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'Ray', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


