function [fitresult, gof] = create2RayFit_Res(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for '2-Rayleigh sum' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Dec-2019 19:01:16


%% Fit: '2-Rayleigh sum'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '((x./s1^2).*exp(-x.^2./(2*s1^2)))*bin_width+w2*((x./s2^2).*exp(-x.^2./(2*s2^2)))*bin_width', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.913375856139019 0.0975404049994095 0.278498218867048 0.964888535199277];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', '2-Rayleigh sum' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', '2-Rayleigh sum', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, '2-Rayleigh sum - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


